export const PERMISSIONS = {
  CREATE_ORG: 'CREATE_ORG',
  VIEW_ORG: 'VIEW_ORG',
  ASSIGN_COURSE: 'ASSIGN_COURSE',
  ISSUE_LICENSE: 'ISSUE_LICENSE',
  MANAGE_ROBOTS: 'MANAGE_ROBOTS',
  UPLOAD_PLATFORM_CONTENT: 'UPLOAD_PLATFORM_CONTENT',
  UPLOAD_ORG_CONTENT: 'UPLOAD_ORG_CONTENT',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
};
